#!/bin/bash

rofi -modi emoji -show emoji -emoji-mode copy -theme ~/.config/rofi/scripts/emoji/style.rasi -emoji-format '<span font_desc="Noto Color Emoji 35">{emoji}</span> <span weight="bold">{name}</span> [<span size="small">({group})</span>]'
