###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
# $terminal = kitty
# $terminal = alacritty
# $terminal = ghostty
$terminal = env GTK_IM_MODULE=simple ghostty
$fileManager = nemo # dolphin
$menu = wofi --show drun
$editor = alacritty -e nvim
# $chrome = google-chrome-stable --use-gl=desktop --enable-features=UseOzonePlatform --ozone-platform=wayland
# $chrome = env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland
# $chrome = google-chrome-stable --enable-features=SkiaGraphite,Vulkan --ozone-platform=x11 --use-angle=vulkan --enable-webgpu-developer-features --enable-skia-graphite --enable-unsafe-webgpu
$chrome = google-chrome-stable --enable-features=SkiaGraphite,Vulkan --ozone-platform=x11 --use-angle=vulkan
$browser = $chrome