#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    # kb_layout = us
    # kb_variant = intl
    # kb_model =
    # kb_options =
    # kb_rules =
 
     follow_mouse = 1

     sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
         natural_scroll = on
     }
}

#############################################
###  CONFIGURAÇÕES ESPECÍFICAS DE TECLADO ###
#############################################

# Teclado do Notebook -> Layout Brasileiro ABNT2
device {
    name = at-translated-set-2-keyboard
    kb_layout = br
    kb_variant = abnt2
}

# Teclado Keychron K7 Pro -> Layout Americano Internacional
device {
    name = keychron-k7-pro-keyboard
    kb_layout = us
    kb_variant = intl
}

# https://wiki.hypr.land/Configuring/Variables/#gestures
gesture = 3, horizontal, workspace
gesture = 3, down, mod: ALT, close
gesture = 3, up, mod: SUPER, scale: 1.5, fullscreen
# gesture = 3, left, scale: 1.5, float

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}


