################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# monitor=,preferred,auto,auto

# Monitor Esquerdo (tela do Notebook Legion)
# A posicao x é 0. A posicao y é 0
monitor = eDP-1, 1920x1080@60, 0x0, 1.0

# Monitor do centro (AOC 27G2G4 - HDMI-A-1)
# A posição x é 1920. A posição y é 0.
monitor = HDMI-A-1, 1920x1080@60, 1920x0, 1.0


# Monitor da direita (Dell Alienware - DP-2)
# A posição x é a largura do monitor da esquerda + a largura do monitor do centro (1920 + 1920 = 3840)
# A posição y é 0.
monitor = DP-2, 2560x1440@60, 3840x0, 1.0



